spring:
  application:
    name: gateway-zuul

server:
  port: 8762

eureka:
  client:
    fetch-register: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
zuul:
  routes:
    auth:
      path: /auth/**
      service-id: auth
    nutri:
      path: /api/nutricionista/**
      service-id: nutri
    personal:
      path: /api/personal/**
      service-id: personal
    aluno:
      path: /api/aluno/**
      service-id: aluno

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

##configura��es de timeout do Zuul
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
#ribbon.ConnectTimeout=10000
#ribbon.ReadTimeout=20000
#
##definindo as rotas dos serivos rodando do eureka server como clients
#zuul.routes.worker.service-id=auth
#zuul.routes.worker.path=/auth/**